CLIPS = [
    "top enemigo",
    "faker what was that",
    "son robots",
    "im a problem",
    "todos los dias igual",
    "autoataques",
    "matale",
    "cliente de mierda",
    "my team is so bad",
    "que haces putita",
    "rock solid",
    "tengo furbo",
    "chao concha",
    "puse el turbo",
    "con los terrorista",
    "no mana",
    "demacia",
    "golaso",
    "we got him",
    "vamo a juga",
    "nasus is stacking",
    "pmp",
    "atras",
    "we smell pennies",
    "hacen cosas",
    "somos sentimientos",
    "hacemos lo que podemos",
    "es el vecino",
    "venga adelante",
    "mucho espanoles",
    "piensan antes",
    "vaso",
    "cuanto peor mejor",
    "hee hee",
    "snap back to reality",
    "i lost my words",
    "porfaa",
    "jajano",
    "onii chan",
    "ayaya",
    "yuupi",
    "vaya ppc",
    "no que va",
    "rayita",
    "que ha hecho",
    "zz",
    "el gobierno",
    "jijija",
    "en mp3",
    "fbi open up",
    "risitas",
    "piruriru",
    "es un tio",
    "headshot",
    "bonk",
    "thud",
    "sad violin",
    "wow",
    "phub",
    "de verda",
    "no tio",
    "die little animal",
    "es blissard",
    "esto es el wow",
    "gg wp",
    "no comprender",
    "pero mira",
    "porque blissard",
    "skyfall",
    "vaya ostia",
    "esta gorda",
    "esta grabando",
    "segundo hit",
    "me cago",
    "paguita extra",
]
