CLIPS = {
    "Diego Rager": [
        "ai no se",
        "die little animal",
        "el gobierno",
        "es blissard",
        "es verdad",
        "gg wp",
        "granadeo",
        "luis despierta",
        "nivel de gusano",
        "no comprender",
        "no me chupes",
        "pero mira",
        "porque blissard",
        "primer aviso",
        "que ha hecho",
        "que es eso",
        "que me cago",
        "que pasa toplane",
        "rayita",
        "ready pa la guerra",
        "si te fumas",
        "toma tonto",
        "un ivan",
        "vaya ostia",
        "ya no hay toplane",
    ],
    "Marto": [
        "cona mala",
        "esta gorda",
        "esta grabando",
        "no mana",
        "perra mala",
        "segundo hit",
        "skyfall",
        "ziggs musulman",
    ],
    "Luis Master": [
        "abuela momificada",
        "cockemon",
        "criminal",
        "de frente",
        "empanado",
        "esquivo automatico",
        "estas burlao",
        "me cago en",
        "me esta poniendo filipino",
        "imperdonable",
        "ni dios",
        "no se hablar",
        "pronunciar mi nombre",
        "toma",
    ],
    "luckyGiorgi0": [
        "donde esta toplane",
        "estabas a limite de rango",
        "vaya ppc",
        "vete a tomar",
        "zz",
    ],
    "Iván Predictor": [
        "a",
        "avisado estas",
        "el bicho",
        "esto es el wow",
        "es verdad ivan",
        "me cago",
        "no lo hagas",
        "no que va",
    ],
    "Braischan": [
        "paguita extra",
    ],
    "Adri Ranger": [
        "among as",
        "donde esta el rango",
        "falta dano",
        "lo sabia",
        "no se cuanto rango",
        "pinchito",
        "que esquivada",
        "que nos vienen",
    ],
    "Dani Julio": [
        "buenisimo julio",
    ],
    "Fytruzas": [
        "comeme",
    ],
    "Elpior": [
        "cliente de mierda",
        "top enemigo",
        "my team is so bad",
        "porfaa",
        "riot",
        "salta palante",
    ],
    "Nissaxter": [
        "autoataques",
        "de verda",
        "matale",
        "no tio",
        "todos los dias igual",
    ],
    "Tyler Uno": [
        "im a problem",
        "nasus is stacking",
        "you have no mana",
    ],
    "Efectos de Sonido": [
        "ayaya",
        "bonk",
        "headshot",
        "en mp3",
        "fbi open up",
        "jijija",
        "onii chan",
        "piruriru",
        "phub",
        "risitas",
        "sad violin",
        "thud",
        "wow",
    ],
    "Paridas Varias": [
        "atras",
        "chao concha",
        "es un tio",
        "golaso",
        "jajano",
        "ni de cona",
        "puse el turbo",
        "tengo furbo",
        "vamo a juga",
        "we got him",
        "we smell pennies",
    ],
    "Plays LoL": [
        "faker what was that",
        "i lost my words",
        "que haces putita",
        "son robots",
    ],
    "Voces LoL": [
        "demacia",
        "rock solid",
        "yuupi",
    ],
    "Politics": [
        "cuanto peor mejor",
        "es el vecino",
        "hacemos lo que podemos",
        "hacen cosas",
        "mucho espanoles",
        "somos sentimientos",
        "piensan antes",
        "pmp",
        "vaso",
        "venga adelante",
    ],
    "Canciones": [
        "con los terrorista",
        "hee hee",
        "snap back to reality",
    ],
}
